package recette.routing;

/**
 *
 * @author dominique huguenin (dominique.huguenin at rpn.ch)
 */
public enum ActionPage {
    QUITTER,
    FILTRER,
    VISUALISER,
    MODIFIER,
    VALIDER_MODIFICATION,
    CREER,
    VALIDER_CREATION,
    SUPPRIMER,
    VALIDER_SUPPRESSION,
    QUITTER_RECHERCHE,
    RECHERCHER_RECETTE,
    SUPPRIMER_RECETTE,
    SELECTIONNER_RECETTE,
    RECHERCHER_INGREDIENT,
    SELECTIONNER_INGREDIENT,
    SUPPRIMER_INGREDIENT,
    RECHERCHER_UNITE,
    SELECTIONNER_UNITE,
    SUPPRIMER_UNITE,
    AJOUTER_COMPOSANT,
    SUPPRIMER_COMPOSANT

}
